In [ ]:
## installed necessary lib

import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [7]:
import pandas as pd

file_path = "/Users/swathisri.ks/Documents/International_Debt_Analytics_DA2/data/raw/IDS_SeriesMetaData.csv"

ids_seriesmetadata = pd.read_csv(
    file_path,
    encoding="latin1"
)

print("CSV loaded successfully!")
print("Shape:", ids_seriesmetadata.shape)

display(ids_seriesmetadata.head())

CSV loaded successfully!
Shape: (574, 12)

,Code,License Type,Indicator Name,Short definition,Long definition,Source,Topic,Dataset,Periodicity,Aggregation method,Limitations and exceptions,General comments
0,DT.GPA.DPPG,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
1,DT.GPA.OFFT,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
2,DT.GPA.PRVT,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
3,DT.GRE.DPPG,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
4,DT.GRE.OFFT,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN

In [6]:
import pandas as pd

file_path = "/Users/swathisri.ks/Documents/International_Debt_Analytics_DA2/data/raw/IDS_FootNoteMetaData.csv"

ids_footnotemetadata = pd.read_csv(
    file_path,
    encoding="latin1"
)

print("CSV loaded successfully!")
print("Shape:", ids_footnotemetadata.shape)

display(ids_footnotemetadata.head())

CSV loaded successfully!
Shape: (2673, 5)

,Type,Country Code,Series Code,Time Code,Description
0,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2024 (YR2024),Data on Personal Transfers and Compensation of...
1,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2023 (YR2023),Source: United Nations Conference on Trade and...
2,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2021 (YR2021),Source: United Nations Conference on Trade and...
3,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2022 (YR2022),Source: United Nations Conference on Trade and...
4,FootNote,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",2021 (YR2021),Source: United Nations Conference on Trade and...

In [5]:
import pandas as pd

file_path = "/Users/swathisri.ks/Documents/International_Debt_Analytics_DA2/data/raw/IDS_CountryMetaData.csv"

ids_countrymetadata = pd.read_csv(
    file_path,
    encoding="latin1"
)

print("CSV loaded successfully!")
print("Shape:", ids_countrymetadata.shape)

display(ids_countrymetadata.head())

CSV loaded successfully!
Shape: (134, 30)

,Code,Long Name,Income Group,Region,Lending category,Other groups,Currency Unit,Latest population census,Latest household survey,Special Notes,...,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,2-alpha code,WB-2 code,Table Name,Short Name
0,AFG,Islamic State of Afghanistan,Low income,Middle East & North Africa,IDA,HIPC,Afghan afghani,1979,Multiple Indicator Cluster Survey 2022-2023,The reporting period for national accounts dat...,...,"Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0,2000.0,AF,AF,Afghanistan,Afghanistan
1,ALB,Republic of Albania,Upper middle income,Europe & Central Asia,IBRD,NaN,Albanian lek,2023,Demographic and Health Survey 2017 - 2018,NaN,...,Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2018.0,2006.0,AL,AL,Albania,Albania
2,DZA,People's Democratic Republic of Algeria,Upper middle income,Middle East & North Africa,IBRD,NaN,Algerian dinar,2022,Multiple Indicator Cluster Survey 2018-2019,NaN,...,"Integrated household survey (IHS), 2011",NaN,NaN,2010.0,2017.0,2012.0,DZ,DZ,Algeria,Algeria
3,AGO,People's Republic of Angola,Lower middle income,Sub-Saharan Africa,IBRD,NaN,Angolan kwanza,2014,Demographic and Health Survey 2015/16,The World Bank systematically assesses the app...,...,"Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2018.0,2005.0,AO,AO,Angola,Angola
4,ARG,Argentine Republic,Upper middle income,Latin America & Caribbean,IBRD,NaN,Argentine peso,2022,Multiple Indicator Cluster Survey 2019-2020,The World Bank systematically assesses the app...,...,"Integrated household survey (IHS), 2016",Yes,2008,2002.0,2018.0,2011.0,AR,AR,Argentina,Argentina

In [4]:
import pandas as pd

file_path = "/Users/swathisri.ks/Documents/International_Debt_Analytics_DA2/data/raw/IDS_ALLCountries_Data.csv"

ids_allcountries_data = pd.read_csv(
    file_path,
    encoding="latin1"
)

print("CSV loaded successfully!")
print("Shape:", ids_allcountries_data.shape)

display(ids_allcountries_data.head())

CSV loaded successfully!
Shape: (62983, 39)

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,2000,2001,2002,2003,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032
0,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.DPPG,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.OFFT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.PRVT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.DPPG,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.OFFT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
import pandas as pd

file_path = "/Users/swathisri.ks/Documents/International_Debt_Analytics_DA2/data/raw/Country_Series_Metadata.csv"

country_series_metadata = pd.read_csv(
    file_path,
    encoding="latin1"
)

print("CSV loaded successfully!")
print("Shape:", country_series_metadata.shape)

display(country_series_metadata.head())

CSV loaded successfully!
Shape: (375, 4)

,Type,Country Code,Series Code,Description
0,Country-Series,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
1,Country-Series,Afghanistan (AFG),"Population, total (SP.POP.TOTL)",Data source: United Nations World Population P...
2,Country-Series,Afghanistan (AFG),"External debt stocks, total (DOD, current US$)...","Long-term public and publicly guaranteed, long..."
3,Country-Series,Angola (AGO),"External debt stocks, total (DOD, current US$)...",Long-term public and publicly guaranteed debt ...
4,Country-Series,Angola (AGO),"Population, total (SP.POP.TOTL)",Data source: United Nations World Population P...

In [ ]:
## TOTAL ROW COUNT

#country_series_metadata.shape[0] ##375

#ids_allcountries_data.shape[0] ##62983

#ids_countrymetadata.shape[0] # 134

#ids_seriesmetadata.shape[0] #574

#ids_footnotemetadata.shape[0] #2673

2673

In [27]:
ids_allcountries_data.columns.tolist()

['country_name',
 'country_code',
 'counterpart_area_name',
 'counterpart_area_code',
 'series_name',
 'series_code',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2025',
 '2026']

In [ ]:
## data preprocessing , cleaning, null-handling delete for "ids_allcountries_data" FILE

#STEP 1 Formatting column names 
ids_allcountries_data.columns = (
    ids_allcountries_data.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
    .str.replace("-", "_", regex=False)
)

print(ids_allcountries_data.columns.tolist())

['country_name', 'country_code', 'counterpart_area_name', 'counterpart_area_code', 'series_name', 'series_code', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028', '2029', '2030', '2031', '2032']

In [23]:
# Step 2 — Remove 2027–2032

future_years = [str(year) for year in range(2027, 2033)]

ids_allcountries_data = ids_allcountries_data.drop(
    columns=[year for year in future_years if year in ids_allcountries_data.columns]
)

In [52]:
#Step 3 — Convert data column-wise to row-wise,

id_columns = [
    "country_name",
    "country_code",
    "counterpart_area_name",
    "counterpart_area_code",
    "series_name",
    "series_code"
]

year_columns = [
    str(year)
    for year in range(2000, 2027)
    if str(year) in ids_allcountries_data.columns
]

df_long = ids_allcountries_data.melt(
    id_vars=id_columns,
    value_vars=year_columns,
    var_name="year",
    value_name="debt_value"
)

In [38]:
df_long.head(10)

,country_name,country_code,counterpart_area_name,counterpart_area_code,series_name,series_code,year,debt_value
0,Afghanistan,AFG,World,WLD,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2000,3.873397e+09
1,Afghanistan,AFG,World,WLD,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2001,3.873397e+09
2,Afghanistan,AFG,World,WLD,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2002,3.873397e+09
3,Afghanistan,AFG,World,WLD,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2003,3.873397e+09
4,Afghanistan,AFG,World,WLD,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2004,3.873397e+09
5,Afghanistan,AFG,World,WLD,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2005,3.873397e+09
6,Afghanistan,AFG,World,WLD,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2006,3.873397e+09
7,Afghanistan,AFG,World,WLD,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2007,3.873397e+09
8,Afghanistan,AFG,World,WLD,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2008,3.873397e+09
9,Afghanistan,AFG,World,WLD,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2009,4.194029e+09

In [53]:
## changed column data type for (year , debt_value)
df_long["year"] = pd.to_numeric(
    df_long["year"],
    errors="coerce"
)

df_long["debt_value"] = pd.to_numeric(
    df_long["debt_value"],
    errors="coerce"
)

In [34]:
df_long.dtypes

country_name                 str
country_code                 str
counterpart_area_name        str
counterpart_area_code        str
series_name                  str
series_code                  str
year                       int64
debt_value               float64
dtype: object

In [60]:
## NULL VALUE CHECKING

df_long.isnull().sum()

country_name             0
country_code             0
counterpart_area_name    0
counterpart_area_code    0
series_name              0
series_code              0
year                     0
debt_value               0
dtype: int64

In [36]:
df_long = df_long.sort_values(
    ["country_code", "series_code", "year"]
).reset_index(drop=True)

In [37]:
## APPLY ffill() + bfill()

df_long["debt_value"] = (
    df_long
    .groupby(["country_code", "series_code"])["debt_value"]
    .transform(lambda x: x.ffill().bfill())
)

In [48]:
df_long[
    df_long[
        [
            "country_name",
            "country_code",
            "series_name",
            "series_code",
            "debt_value"
        ]
    ].isnull().all(axis=1)
].shape

(0, 8)

In [51]:
df_long[
    df_long["country_code"].isnull()
][
    [
        "country_name",
        "country_code",
        "counterpart_area_name",
        "counterpart_area_code",
        "series_name",
        "series_code",
        "year",
        "debt_value"
    ]
].head(20)

NameError: name 'df_long' is not defined

In [ ]:
## Remove all rows where country_code is NULL 

df_long = df_long.dropna(
    subset=["country_code"]
).reset_index(drop=True)

In [ ]:
# Remove completely empty groups
df_long = df_long[
    df_long.groupby(
        ["country_code", "counterpart_area_code", "series_code"]
    )["debt_value"]
    .transform("count") > 0
].reset_index(drop=True)

In [ ]:
## No null values
df_long[
    df_long["debt_value"].isnull()
].head(20)

Empty DataFrame
Columns: [country_name, country_code, counterpart_area_name, counterpart_area_code, series_name, series_code, year, debt_value]
Index: []

In [68]:
print("country_series_metadata")
print(country_series_metadata.columns.tolist())

print("\nids_countrymetadata")
print(ids_countrymetadata.columns.tolist())

print("\nids_seriesmetadata")
print(ids_seriesmetadata.columns.tolist())

print("\nids_footnotemetadata")
print(ids_footnotemetadata.columns.tolist())

country_series_metadata
['type', 'country_code', 'series_code', 'description']

ids_countrymetadata
['code', 'long_name', 'income_group', 'region', 'lending_category', 'other_groups', 'currency_unit', 'latest_population_census', 'latest_household_survey', 'special_notes', 'national_accounts_base_year', 'national_accounts_reference_year', 'system_of_national_accounts', 'sna_price_valuation', 'ppp_survey_years', 'balance_of_payments_manual_in_use', 'external_debt_reporting_status', 'system_of_trade', 'government_accounting_concept', 'imf_data_dissemination_standard', 'source_of_most_recent_income_and_expenditure_data', 'vital_registration_complete', 'latest_agricultural_census', 'latest_industrial_data', 'latest_trade_data', 'latest_water_withdrawal_data', '2_alpha_code', 'wb_2_code', 'table_name', 'short_name']

ids_seriesmetadata
['code', 'license_type', 'indicator_name', 'short_definition', 'long_definition', 'source', 'topic', 'dataset', 'periodicity', 'aggregation_method', 'limitations_and_exceptions', 'general_comments']

ids_footnotemetadata
['type', 'country_code', 'series_code', 'time_code', 'description']

In [67]:
## column formating for remaining CSV FILES

def clean_column_names(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
    )
    return df


country_series_metadata = clean_column_names(country_series_metadata)
ids_countrymetadata = clean_column_names(ids_countrymetadata)
ids_seriesmetadata = clean_column_names(ids_seriesmetadata)
ids_footnotemetadata = clean_column_names(ids_footnotemetadata)

In [70]:
print("COUNTRY SERIES METADATA")
print(country_series_metadata.dtypes)

print("\nCOUNTRY METADATA")
print(ids_countrymetadata.dtypes)

print("\nSERIES METADATA")
print(ids_seriesmetadata.dtypes)

print("\nFOOTNOTE METADATA")
print(ids_footnotemetadata.dtypes)

COUNTRY SERIES METADATA
type            str
country_code    str
series_code     str
description     str
dtype: object

COUNTRY METADATA
code                                                     str
long_name                                                str
income_group                                             str
region                                                   str
lending_category                                         str
other_groups                                             str
currency_unit                                            str
latest_population_census                                 str
latest_household_survey                                  str
special_notes                                            str
national_accounts_base_year                              str
national_accounts_reference_year                     float64
system_of_national_accounts                              str
sna_price_valuation                                      str
ppp_survey_years                                         str
balance_of_payments_manual_in_use                        str
external_debt_reporting_status                           str
system_of_trade                                          str
government_accounting_concept                            str
imf_data_dissemination_standard                          str
source_of_most_recent_income_and_expenditure_data        str
vital_registration_complete                              str
latest_agricultural_census                               str
latest_industrial_data                               float64
latest_trade_data                                    float64
latest_water_withdrawal_data                         float64
2_alpha_code                                             str
wb_2_code                                                str
table_name                                               str
short_name                                               str
dtype: object

SERIES METADATA
code                          str
license_type                  str
indicator_name                str
short_definition              str
long_definition               str
source                        str
topic                         str
dataset                       str
periodicity                   str
aggregation_method            str
limitations_and_exceptions    str
general_comments              str
dtype: object

FOOTNOTE METADATA
type            str
country_code    str
series_code     str
time_code       str
description     str
dtype: object

In [78]:
print("COUNTRY SERIES METADATA")
print(country_series_metadata.isnull().sum())

print("\nCOUNTRY METADATA")
print(ids_countrymetadata.isnull().sum())

print("\nSERIES METADATA")
print(ids_seriesmetadata.isnull().sum())

print("\nFOOTNOTE METADATA")
print(ids_footnotemetadata.isnull().sum())

COUNTRY SERIES METADATA
type            0
country_code    0
series_code     0
description     0
dtype: int64

COUNTRY METADATA
code                                                  0
long_name                                             0
income_group                                         15
region                                               14
lending_category                                     14
other_groups                                         94
currency_unit                                        14
latest_population_census                             16
latest_household_survey                              14
special_notes                                        74
national_accounts_base_year                          14
national_accounts_reference_year                     95
system_of_national_accounts                          14
sna_price_valuation                                  14
ppp_survey_years                                     18
balance_of_payments_manual_in_use                    16
external_debt_reporting_status                       14
system_of_trade                                      34
government_accounting_concept                        37
imf_data_dissemination_standard                      17
source_of_most_recent_income_and_expenditure_data    18
vital_registration_complete                          98
latest_agricultural_census                           63
latest_industrial_data                               49
latest_trade_data                                    21
latest_water_withdrawal_data                         22
2_alpha_code                                          0
wb_2_code                                             0
table_name                                            0
short_name                                            0
dtype: int64

SERIES METADATA
code                  0
indicator_name        0
short_definition      2
long_definition       0
source                0
topic                 0
dataset               1
periodicity           0
aggregation_method    0
dtype: int64

FOOTNOTE METADATA
type            0
country_code    0
series_code     0
time_code       0
description     0
dtype: int64

In [76]:
null_percentage = ids_seriesmetadata.isnull().mean() * 100

columns_to_remove = null_percentage[
    null_percentage > 90
].index

print(columns_to_remove.tolist())

[]

In [80]:
country_null_percentage = (
    ids_countrymetadata.isnull().mean() * 100
).sort_values(ascending=False)

country_null_percentage[
    country_null_percentage > 0
]

vital_registration_complete                          73.134328
national_accounts_reference_year                     70.895522
other_groups                                         70.149254
special_notes                                        55.223881
latest_agricultural_census                           47.014925
latest_industrial_data                               36.567164
government_accounting_concept                        27.611940
system_of_trade                                      25.373134
latest_water_withdrawal_data                         16.417910
latest_trade_data                                    15.671642
ppp_survey_years                                     13.432836
source_of_most_recent_income_and_expenditure_data    13.432836
imf_data_dissemination_standard                      12.686567
balance_of_payments_manual_in_use                    11.940299
latest_population_census                             11.940299
income_group                                         11.194030
external_debt_reporting_status                       10.447761
system_of_national_accounts                          10.447761
national_accounts_base_year                          10.447761
latest_household_survey                              10.447761
currency_unit                                        10.447761
lending_category                                     10.447761
region                                               10.447761
sna_price_valuation                                  10.447761
dtype: float64

In [60]:
cleaned_path = "/Users/swathisri.ks/Documents/International_Debt_Analytics_DA2/data/processed/ids_allcountries_data.csv"

df_long.to_csv(
    cleaned_path,
    index=False
)

print("Cleaned file saved successfully!")
print(cleaned_path)

Cleaned file saved successfully!
/Users/swathisri.ks/Documents/International_Debt_Analytics_DA2/data/processed/ids_allcountries_data.csv

In [ ]:
print("COUNTRY SERIES METADATA")
print(country_series_metadata.isnull().sum())

print("\nCOUNTRY METADATA")
print(ids_countrymetadata.isnull().sum())

print("\nSERIES METADATA")
print(ids_seriesmetadata.isnull().sum())

print("\nFOOTNOTE METADATA")
print(ids_footnotemetadata.isnull().sum())

In [ ]:
## 

import pandas as pd
%pip install matplotlib seaborn
import seaborn as sns

In [89]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

In [13]:
import sys
!{sys.executable} -m pip install mysql-connector-python

Collecting mysql-connector-python
  Using cached mysql_connector_python-26.7.0-cp313-cp313-macosx_14_0_arm64.whl.metadata (11 kB)
Using cached mysql_connector_python-26.7.0-cp313-cp313-macosx_14_0_arm64.whl (20.3 MB)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip

In [19]:
import mysql.connector

print("MySQL connector working!")

MySQL connector working!

In [40]:
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Swathi22@",
    database="international_debt",
    port=3306
)

print("Connected to international_debt")

Connected to international_debt

In [22]:
cursor = connection.cursor()

cursor.execute("CREATE DATABASE international_debt")

print("Database created successfully!")

Database created successfully!

In [23]:
cursor.execute("SHOW DATABASES")

for db in cursor.fetchall():
    print(db[0])

information_schema
international_debt
mysql
performance_schema
sql_learning
SupermarketDB
sys

In [33]:
cursor.execute("USE international_debt")

In [121]:
cursor.execute("SHOW TABLES")

for table in cursor.fetchall():
    print(table[0])

allcountries_debt_data
country_series_metadata
ids_countrymetadata
ids_footnotemetadata
ids_seriesmetadata_clean
top_10_countries_debt

In [27]:
import pandas as pd
import os

In [62]:
data_path = "/Users/swathisri.ks/Documents/International_Debt_Analytics_DA2/data/processed/"
os.listdir(data_path)

['country_series_metadata.csv',
 'ids_seriesmetadata_clean.csv',
 'ids_footnotemetadata.csv',
 'ids_allcountries_data.csv',
 'ids_countrymetadata.csv']

In [63]:
import pandas as pd

country_series_metadata = pd.read_csv(
    data_path + "country_series_metadata.csv"
)

ids_allcountries_data = pd.read_csv(
    data_path + "ids_allcountries_data.csv"
)

ids_countrymetadata = pd.read_csv(
    data_path + "ids_countrymetadata.csv"
)

ids_footnotemetadata = pd.read_csv(
    data_path + "ids_footnotemetadata.csv"
)

ids_seriesmetadata_clean = pd.read_csv(
    data_path + "ids_seriesmetadata_clean.csv"
)

In [65]:
print("country_series_metadata:", country_series_metadata.shape)
print("ids_allcountries_data:", ids_allcountries_data.shape)
print("ids_countrymetadata:", ids_countrymetadata.shape)
print("ids_footnotemetadata:", ids_footnotemetadata.shape)
print("ids_seriesmetadata_clean:", ids_seriesmetadata_clean.shape)

country_series_metadata: (375, 4)
ids_allcountries_data: (1700487, 8)
ids_countrymetadata: (134, 30)
ids_footnotemetadata: (2673, 5)
ids_seriesmetadata_clean: (574, 9)

In [36]:
cursor = connection.cursor()

cursor.execute("SELECT DATABASE()")

print(cursor.fetchone())

('international_debt',)

In [37]:
cursor.execute("USE international_debt")

In [38]:
cursor.execute("SHOW TABLES")

tables = cursor.fetchall()

for table in tables:
    print(table[0])

In [42]:
import sys
!{sys.executable} -m pip install sqlalchemy

Collecting sqlalchemy
  Using cached sqlalchemy-2.0.52-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.6 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/swathisri.ks/Library/Python/3.13/lib/python/site-packages (from sqlalchemy) (4.16.0)
Using cached sqlalchemy-2.0.52-cp313-cp313-macosx_11_0_arm64.whl (2.2 MB)
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-2.0.52

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip

In [43]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:Swathi22@@localhost:3306/international_debt"
)

In [44]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

connection_url = URL.create(
    "mysql+mysqlconnector",
    username="root",
    password="Swathi22@",
    host="localhost",
    port=3306,
    database="international_debt"
)

engine = create_engine(connection_url)

print("SQLAlchemy engine created successfully!")

SQLAlchemy engine created successfully!

In [45]:
with engine.connect() as conn:
    result = conn.exec_driver_sql("SELECT DATABASE()")
    print(result.fetchone())

('international_debt',)

In [46]:
country_series_metadata.to_sql(
    "country_series_metadata",
    con=engine,
    if_exists="replace",
    index=False
)

ids_allcountries_data.to_sql(
    "ids_allcountries_data",
    con=engine,
    if_exists="replace",
    index=False
)

ids_countrymetadata.to_sql(
    "ids_countrymetadata",
    con=engine,
    if_exists="replace",
    index=False
)

ids_footnotemetadata.to_sql(
    "ids_footnotemetadata",
    con=engine,
    if_exists="replace",
    index=False
)

ids_seriesmetadata_clean.to_sql(
    "ids_seriesmetadata_clean",
    con=engine,
    if_exists="replace",
    index=False
)

print("All 5 tables inserted!")

All 5 tables inserted!

In [70]:
cursor = connection.cursor()
cursor.execute("SHOW TABLES")

for table in cursor.fetchall():
    print(table[0])

allcountries_debt_data
country_series_metadata
ids_countrymetadata
ids_footnotemetadata
ids_seriesmetadata_clean

In [49]:
%whos DataFrame

Variable                   Type         Data/Info
-------------------------------------------------
country_series_metadata    DataFrame    Shape: (375, 4)
ids_allcountries_data      DataFrame    Shape: (62981, 33)
ids_countrymetadata        DataFrame    Shape: (134, 30)
ids_footnotemetadata       DataFrame    Shape: (2673, 5)
ids_seriesmetadata_clean   DataFrame    Shape: (574, 9)

In [82]:
q1 = pd.read_sql("""
    SELECT DISTINCT country_name
    FROM allcountries_debt_data
    WHERE country_name IS NOT NULL
    ORDER BY country_name;
""", connection)

display(q1)

/var/folders/c3/nx9p1xn95bgg5cxm9x2h6xw00000gp/T/ipykernel_5992/261569364.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  q1 = pd.read_sql("""

    country_name
0    Afghanistan
1        Albania
2        Algeria
3         Angola
4      Argentina
..           ...
131      Vanuatu
132     Viet Nam
133  Yemen, Rep.
134       Zambia
135     Zimbabwe

[136 rows x 1 columns]

In [83]:
q2 = pd.read_sql("""
    SELECT COUNT(DISTINCT country_name) AS total_countries
    FROM allcountries_debt_data
    WHERE country_name IS NOT NULL;
""", connection)

display(q2)

/var/folders/c3/nx9p1xn95bgg5cxm9x2h6xw00000gp/T/ipykernel_5992/1623257668.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  q2 = pd.read_sql("""

   total_countries
0              136

In [84]:
q3 = pd.read_sql("""
    SELECT COUNT(DISTINCT series_name) AS total_indicators
    FROM allcountries_debt_data
    WHERE series_name IS NOT NULL;
""", connection)

display(q3)

/var/folders/c3/nx9p1xn95bgg5cxm9x2h6xw00000gp/T/ipykernel_5992/1852970012.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  q3 = pd.read_sql("""

   total_indicators
0               576

In [85]:
q4 = pd.read_sql("""
    SELECT *
    FROM allcountries_debt_data
    LIMIT 10;
""", connection)

display(q4)

/var/folders/c3/nx9p1xn95bgg5cxm9x2h6xw00000gp/T/ipykernel_5992/1908364031.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  q4 = pd.read_sql("""

,country_name,country_code,counterpart_area_name,counterpart_area_code,series_name,series_code,year,debt_value
0,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.DPPG,2000,None
1,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.OFFT,2000,None
2,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.PRVT,2000,None
3,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.DPPG,2000,None
4,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.OFFT,2000,None
5,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.PRVT,2000,None
6,Afghanistan,AFG,World,WLD,Average interest on new external debt commitme...,DT.INR.DPPG,2000,None
7,Afghanistan,AFG,World,WLD,Average interest on new external debt commitme...,DT.INR.OFFT,2000,None
8,Afghanistan,AFG,World,WLD,Average interest on new external debt commitme...,DT.INR.PRVT,2000,None
9,Afghanistan,AFG,World,WLD,Average maturity on new external debt commitme...,DT.MAT.DPPG,2000,None

In [86]:
q5 = pd.read_sql("""
    SELECT 
        SUM(debt_value) AS total_global_debt
    FROM allcountries_debt_data;
""", connection)

display(q5)

/var/folders/c3/nx9p1xn95bgg5cxm9x2h6xw00000gp/T/ipykernel_5992/1390952754.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  q5 = pd.read_sql("""

   total_global_debt
0       1.246382e+16

In [87]:
q6 = pd.read_sql("""
    SELECT DISTINCT series_name
    FROM allcountries_debt_data
    WHERE series_name IS NOT NULL
    ORDER BY series_name;
""", connection)

display(q6)

/var/folders/c3/nx9p1xn95bgg5cxm9x2h6xw00000gp/T/ipykernel_5992/758586785.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  q6 = pd.read_sql("""

                                           series_name
0    Average grace period on new external debt comm...
1    Average grace period on new external debt comm...
2    Average grace period on new external debt comm...
3    Average grant element on new external debt com...
4    Average grant element on new external debt com...
..                                                 ...
571  Undisbursed external debt, official creditors ...
572  Undisbursed external debt, private creditors (...
573  Undisbursed external debt, total (UND, current...
574               Use of IMF credit (DOD, current US$)
575  Use of IMF credit and SDR allocations (DOD, cu...

[576 rows x 1 columns]

In [88]:
q7 = pd.read_sql("""
    SELECT 
        country_name,
        COUNT(*) AS record_count
    FROM allcountries_debt_data
    WHERE country_name IS NOT NULL
    GROUP BY country_name
    ORDER BY record_count DESC;
""", connection)

display(q7)

/var/folders/c3/nx9p1xn95bgg5cxm9x2h6xw00000gp/T/ipykernel_5992/4142806169.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  q7 = pd.read_sql("""

                                          country_name  record_count
0        Europe & Central Asia (excluding high income)         15498
1    Latin America & Caribbean (excluding high income)         15498
2                                  Low & middle income         15498
3                                  Lower middle income         15498
4                                        Middle income         15498
..                                                 ...           ...
131                                            Eritrea          7506
132                                        Timor-Leste          7479
133                                  Equatorial Guinea          7047
134  Data from database: International Debt Statistics            27
135                           Last Updated: 12/03/2025            27

[136 rows x 2 columns]

In [89]:
q8 = pd.read_sql("""
    SELECT *
    FROM allcountries_debt_data
    WHERE debt_value > 1000000000
    ORDER BY debt_value DESC;
""", connection)

display(q8)

/var/folders/c3/nx9p1xn95bgg5cxm9x2h6xw00000gp/T/ipykernel_5992/2903484008.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  q8 = pd.read_sql("""

,country_name,country_code,counterpart_area_name,counterpart_area_code,series_name,series_code,year,debt_value
0,Low & middle income,LMY,World,WLD,GNI (current US$),NY.GNP.MKTP.CD,2024,3.820000e+13
1,Middle income,MIC,World,WLD,GNI (current US$),NY.GNP.MKTP.CD,2024,3.760000e+13
2,Low & middle income,LMY,World,WLD,GNI (current US$),NY.GNP.MKTP.CD,2023,3.680000e+13
3,Middle income,MIC,World,WLD,GNI (current US$),NY.GNP.MKTP.CD,2023,3.630000e+13
4,Low & middle income,LMY,World,WLD,GNI (current US$),NY.GNP.MKTP.CD,2022,3.570000e+13
...,...,...,...,...,...,...,...,...
240187,Pakistan,PAK,World,WLD,"GG, bilateral (TDS, current US$)",DT.TDS.BLAT.GG.CD,2010,1.000018e+09
240188,Pakistan,PAK,World,WLD,"PPG, bilateral (TDS, current US$)",DT.TDS.BLAT.CD,2010,1.000018e+09
240189,Pakistan,PAK,World,WLD,"PS, bilateral (TDS, current US$)",DT.TDS.BLAT.PS.CD,2010,1.000018e+09
240190,Angola,AGO,World,WLD,"PPG, commercial banks (NFL, current US$)",DT.NFL.PCBK.CD,2004,1.000012e+09
240191,Angola,AGO,World,WLD,"PS, commercial banks (NFL, current US$)",DT.NFL.PCBK.PS.CD,2004,1.000012e+09

In [90]:
q9 = pd.read_sql("""
    SELECT
        MIN(debt_value) AS minimum_debt,
        MAX(debt_value) AS maximum_debt,
        AVG(debt_value) AS average_debt
    FROM allcountries_debt_data;
""", connection)

display(q9)

/var/folders/c3/nx9p1xn95bgg5cxm9x2h6xw00000gp/T/ipykernel_5992/3559863317.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  q9 = pd.read_sql("""

   minimum_debt  maximum_debt  average_debt
0 -5.270000e+11  3.820000e+13  9.794364e+09

In [91]:
q10 = pd.read_sql("""
    SELECT COUNT(*) AS total_records
    FROM allcountries_debt_data;
""", connection)

display(q10)

/var/folders/c3/nx9p1xn95bgg5cxm9x2h6xw00000gp/T/ipykernel_5992/3021801411.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  q10 = pd.read_sql("""

   total_records
0        1700487

In [92]:
# INtermidiate

q11 = pd.read_sql("""
    SELECT
        country_name,
        SUM(debt_value) AS total_debt
    FROM allcountries_debt_data
    WHERE country_name IS NOT NULL
    GROUP BY country_name
    ORDER BY total_debt DESC;
""", connection)

display(q11)

/var/folders/c3/nx9p1xn95bgg5cxm9x2h6xw00000gp/T/ipykernel_5992/2513531633.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  q11 = pd.read_sql("""

                                          country_name    total_debt
0                                  Low & middle income  2.382800e+15
1                                        Middle income  2.314371e+15
2                                  Upper middle income  1.699829e+15
3          East Asia & Pacific (excluding high income)  8.877111e+14
4                                  Lower middle income  6.145184e+14
..                                                 ...           ...
131                                            Vanuatu  1.427487e+11
132                              Sao Tome and Principe  1.221988e+11
133                                              Tonga  8.499311e+10
134  Data from database: International Debt Statistics           NaN
135                           Last Updated: 12/03/2025           NaN

[136 rows x 2 columns]

In [94]:
q12 = pd.read_sql("""
    SELECT
        country_name,
        SUM(debt_value) AS total_debt
    FROM allcountries_debt_data
    WHERE country_name IS NOT NULL
      AND debt_value IS NOT NULL
    GROUP BY country_name
    ORDER BY total_debt DESC
    LIMIT 10;
""", engine)

display(q12)

                                        country_name    total_debt
0                                Low & middle income  2.382800e+15
1                                      Middle income  2.314371e+15
2                                Upper middle income  1.699829e+15
3        East Asia & Pacific (excluding high income)  8.877111e+14
4                                Lower middle income  6.145184e+14
5                                              China  6.134844e+14
6  Latin America & Caribbean (excluding high income)  5.762093e+14
7                                          IDA total  2.976229e+14
8      Europe & Central Asia (excluding high income)  2.620929e+14
9                                         South Asia  2.352148e+14

In [95]:
q13 = pd.read_sql("""
    SELECT
        country_name,
        AVG(debt_value) AS average_debt
    FROM allcountries_debt_data
    WHERE country_name IS NOT NULL
      AND debt_value IS NOT NULL
    GROUP BY country_name
    ORDER BY average_debt DESC;
""", engine)

display(q13)

                                    country_name  average_debt
0                            Low & middle income  1.651740e+11
1                                  Middle income  1.605529e+11
2                            Upper middle income  1.185541e+11
3    East Asia & Pacific (excluding high income)  6.586371e+10
4                                          China  5.637607e+10
..                                           ...           ...
129                              Solomon Islands  2.236292e+07
130                                      Vanuatu  2.036649e+07
131                        Sao Tome and Principe  1.776662e+07
132                                     Dominica  1.701911e+07
133                                        Tonga  1.238245e+07

[134 rows x 2 columns]

In [96]:
q14 = pd.read_sql("""
    SELECT
        series_name AS indicator,
        SUM(debt_value) AS total_debt
    FROM allcountries_debt_data
    WHERE series_name IS NOT NULL
      AND debt_value IS NOT NULL
    GROUP BY series_name
    ORDER BY total_debt DESC;
""", engine)

display(q14)

                                             indicator    total_debt
0                                    GNI (current US$)  2.634973e+15
1    Imports of goods, services and primary income ...  7.173482e+14
2    Exports of goods, services and primary income ...  6.729154e+14
3       External debt stocks, total (DOD, current US$)  6.569861e+14
4          Total reserves (includes gold, current US$)  5.483682e+14
..                                                 ...           ...
571                  OPS, bilateral (NTR, current US$) -1.664706e+11
572     PS, other private creditors (NTR, current US$) -1.754345e+11
573    PPG, other private creditors (NTR, current US$) -1.797011e+11
574         OPS, official creditors (NTR, current US$) -2.605065e+11
575        Debt forgiveness or reduction (current US$) -1.938275e+12

[576 rows x 2 columns]

In [97]:
q15 = pd.read_sql("""
    SELECT
        series_name AS indicator,
        SUM(debt_value) AS total_debt
    FROM allcountries_debt_data
    WHERE series_name IS NOT NULL
      AND debt_value IS NOT NULL
    GROUP BY series_name
    ORDER BY total_debt DESC
    LIMIT 1;
""", engine)

display(q15)

           indicator    total_debt
0  GNI (current US$)  2.634973e+15

In [98]:
q16 = pd.read_sql("""
    SELECT
        country_name,
        SUM(debt_value) AS total_debt
    FROM allcountries_debt_data
    WHERE country_name IS NOT NULL
      AND debt_value IS NOT NULL
    GROUP BY country_name
    ORDER BY total_debt ASC
    LIMIT 1;
""", engine)

display(q16)

  country_name    total_debt
0        Tonga  8.499311e+10

In [99]:
q17 = pd.read_sql("""
    SELECT
        country_name,
        series_name AS indicator,
        SUM(debt_value) AS total_debt
    FROM allcountries_debt_data
    WHERE country_name IS NOT NULL
      AND series_name IS NOT NULL
      AND debt_value IS NOT NULL
    GROUP BY country_name, series_name
    ORDER BY total_debt DESC;
""", engine)

display(q17)

,country_name,indicator,total_debt
0,Low & middle income,GNI (current US$),5.123400e+14
1,Middle income,GNI (current US$),5.042800e+14
2,Upper middle income,GNI (current US$),3.992400e+14
3,East Asia & Pacific (excluding high income),GNI (current US$),2.613100e+14
4,China,GNI (current US$),2.206400e+14
...,...,...,...
59633,IDA total,Current account balance (current US$),-9.671256e+11
59634,IDA only,Current account balance (current US$),-9.773572e+11
59635,Brazil,Current account balance (current US$),-9.875853e+11
59636,Lower middle income,Current account balance (current US$),-1.347903e+12
59637,Latin America & Caribbean (excluding high income),Current account balance (current US$),-1.831101e+12

In [100]:
q18 = pd.read_sql("""
    SELECT
        country_name,
        COUNT(DISTINCT series_name) AS indicator_count
    FROM allcountries_debt_data
    WHERE country_name IS NOT NULL
      AND series_name IS NOT NULL
    GROUP BY country_name
    ORDER BY indicator_count DESC;
""", engine)

display(q18)

                                          country_name  indicator_count
0        Europe & Central Asia (excluding high income)              574
1    Latin America & Caribbean (excluding high income)              574
2                                  Low & middle income              574
3                                  Lower middle income              574
4                                        Middle income              574
..                                                 ...              ...
129                                           Cambodia              338
130                                        Afghanistan              297
131                                            Eritrea              278
132                                        Timor-Leste              277
133                                  Equatorial Guinea              261

[134 rows x 2 columns]

In [101]:
q19 = pd.read_sql("""
    SELECT
        country_name,
        SUM(debt_value) AS total_debt
    FROM allcountries_debt_data
    WHERE country_name IS NOT NULL
      AND debt_value IS NOT NULL
    GROUP BY country_name
    HAVING SUM(debt_value) >
    (
        SELECT AVG(country_total)
        FROM
        (
            SELECT
                country_name,
                SUM(debt_value) AS country_total
            FROM allcountries_debt_data
            WHERE country_name IS NOT NULL
              AND debt_value IS NOT NULL
            GROUP BY country_name
        ) AS country_totals
    )
    ORDER BY total_debt DESC;
""", engine)

display(q19)

                                         country_name    total_debt
0                                 Low & middle income  2.382800e+15
1                                       Middle income  2.314371e+15
2                                 Upper middle income  1.699829e+15
3         East Asia & Pacific (excluding high income)  8.877111e+14
4                                 Lower middle income  6.145184e+14
5                                               China  6.134844e+14
6   Latin America & Caribbean (excluding high income)  5.762093e+14
7                                           IDA total  2.976229e+14
8       Europe & Central Asia (excluding high income)  2.620929e+14
9                                          South Asia  2.352148e+14
10         Sub-Saharan Africa (excluding high income)  2.313537e+14
11                                              India  1.878320e+14
12  Middle East, North Africa, Afghanistan & Pakis...  1.868193e+14
13                                             Brazil  1.855443e+14
14                                             Mexico  1.842956e+14
15                                           IDA only  1.818017e+14
16       Least developed countries: UN classification  1.583985e+14
17                                          Indonesia  1.180056e+14
18                                            Turkiye  1.175608e+14

In [102]:
q20 = pd.read_sql("""
    SELECT
        country_name,
        total_debt,
        RANK() OVER (ORDER BY total_debt DESC) AS debt_rank
    FROM
    (
        SELECT
            country_name,
            SUM(debt_value) AS total_debt
        FROM allcountries_debt_data
        WHERE country_name IS NOT NULL
          AND debt_value IS NOT NULL
        GROUP BY country_name
    ) AS country_debt
    ORDER BY debt_rank;
""", engine)

display(q20)

                                    country_name    total_debt  debt_rank
0                            Low & middle income  2.382800e+15          1
1                                  Middle income  2.314371e+15          2
2                            Upper middle income  1.699829e+15          3
3    East Asia & Pacific (excluding high income)  8.877111e+14          4
4                            Lower middle income  6.145184e+14          5
..                                           ...           ...        ...
129                              Solomon Islands  1.583295e+11        130
130                                     Dominica  1.580565e+11        131
131                                      Vanuatu  1.427487e+11        132
132                        Sao Tome and Principe  1.221988e+11        133
133                                        Tonga  8.499311e+10        134

[134 rows x 3 columns]

In [103]:
q21 = pd.read_sql("""
    SELECT
        series_name AS indicator,
        SUM(debt_value) AS total_debt
    FROM allcountries_debt_data
    WHERE series_name IS NOT NULL
      AND debt_value IS NOT NULL
    GROUP BY series_name
    ORDER BY total_debt DESC
    LIMIT 5;
""", engine)

display(q21)

                                           indicator    total_debt
0                                  GNI (current US$)  2.634973e+15
1  Imports of goods, services and primary income ...  7.173482e+14
2  Exports of goods, services and primary income ...  6.729154e+14
3     External debt stocks, total (DOD, current US$)  6.569861e+14
4        Total reserves (includes gold, current US$)  5.483682e+14

In [104]:
q22 = pd.read_sql("""
    SELECT
        country_name,
        SUM(debt_value) AS total_debt,
        ROUND(
            SUM(debt_value) * 100.0 /
            (
                SELECT SUM(debt_value)
                FROM allcountries_debt_data
                WHERE debt_value IS NOT NULL
            ),
            2
        ) AS contribution_percentage
    FROM allcountries_debt_data
    WHERE country_name IS NOT NULL
      AND debt_value IS NOT NULL
    GROUP BY country_name
    ORDER BY contribution_percentage DESC;
""", engine)

display(q22)

,country_name,total_debt,contribution_percentage
0,Low & middle income,2.382800e+15,19.12
1,Middle income,2.314371e+15,18.57
2,Upper middle income,1.699829e+15,13.64
3,East Asia & Pacific (excluding high income),8.877111e+14,7.12
4,Lower middle income,6.145184e+14,4.93
...,...,...,...
129,Timor-Leste,2.102243e+11,0.00
130,Tonga,8.499311e+10,0.00
131,Vanuatu,1.427487e+11,0.00
132,Suriname,6.015575e+11,0.00
133,Equatorial Guinea,2.406565e+11,0.00

In [105]:
q23 = pd.read_sql("""
    SELECT
        indicator,
        country_name,
        total_debt,
        indicator_rank
    FROM
    (
        SELECT
            series_name AS indicator,
            country_name,
            SUM(debt_value) AS total_debt,
            RANK() OVER (
                PARTITION BY series_name
                ORDER BY SUM(debt_value) DESC
            ) AS indicator_rank
        FROM allcountries_debt_data
        WHERE series_name IS NOT NULL
          AND country_name IS NOT NULL
          AND debt_value IS NOT NULL
        GROUP BY series_name, country_name
    ) AS ranked_data
    WHERE indicator_rank <= 3
    ORDER BY indicator, indicator_rank;
""", engine)

display(q23)

,indicator,country_name,total_debt,indicator_rank
0,Average grace period on new external debt comm...,Thailand,3.412972e+02,1
1,Average grace period on new external debt comm...,Indonesia,3.210614e+02,2
2,Average grace period on new external debt comm...,Mexico,3.071533e+02,3
3,Average grace period on new external debt comm...,Bhutan,2.237317e+02,1
4,Average grace period on new external debt comm...,Tanzania,2.172653e+02,2
...,...,...,...,...
1735,"Use of IMF credit (DOD, current US$)",Middle income,1.608354e+12,2
1736,"Use of IMF credit (DOD, current US$)",Upper middle income,1.069349e+12,3
1737,"Use of IMF credit and SDR allocations (DOD, cu...",Low & middle income,3.653507e+12,1
1738,"Use of IMF credit and SDR allocations (DOD, cu...",Middle income,3.426292e+12,2
1739,"Use of IMF credit and SDR allocations (DOD, cu...",Upper middle income,2.314428e+12,3

In [106]:
q24 = pd.read_sql("""
    SELECT
        country_name,
        MAX(debt_value) AS maximum_debt,
        MIN(debt_value) AS minimum_debt,
        MAX(debt_value) - MIN(debt_value) AS debt_difference
    FROM allcountries_debt_data
    WHERE country_name IS NOT NULL
      AND debt_value IS NOT NULL
    GROUP BY country_name
    ORDER BY debt_difference DESC;
""", engine)

display(q24)

,country_name,maximum_debt,minimum_debt,debt_difference
0,Low & middle income,3.820000e+13,-4.930000e+11,3.869300e+13
1,Middle income,3.760000e+13,-4.930000e+11,3.809300e+13
2,Upper middle income,2.990000e+13,-5.270000e+11,3.042700e+13
3,East Asia & Pacific (excluding high income),2.170000e+13,-4.450000e+11,2.214500e+13
4,China,1.860000e+13,-4.450000e+11,1.904500e+13
...,...,...,...,...
129,St. Vincent and the Grenadines,1.147019e+09,-2.299738e+08,1.376992e+09
130,Samoa,1.051480e+09,-1.144461e+08,1.165926e+09
131,Sao Tome and Principe,7.635740e+08,-1.961924e+08,9.597664e+08
132,Dominica,6.915407e+08,-2.588141e+08,9.503548e+08
133,Tonga,5.542691e+08,-9.384590e+07,6.481150e+08

In [107]:
cursor = connection.cursor()

cursor.execute("""
    CREATE OR REPLACE VIEW top_10_countries_debt AS
    SELECT
        country_name,
        SUM(debt_value) AS total_debt
    FROM allcountries_debt_data
    WHERE country_name IS NOT NULL
      AND debt_value IS NOT NULL
    GROUP BY country_name
    ORDER BY total_debt DESC
    LIMIT 10
""")

connection.commit()

print("View created successfully!")

View created successfully!

In [108]:
q25 = pd.read_sql("""
    SELECT *
    FROM top_10_countries_debt
    ORDER BY total_debt DESC;
""", engine)

display(q25)

                                        country_name    total_debt
0                                Low & middle income  2.382800e+15
1                                      Middle income  2.314371e+15
2                                Upper middle income  1.699829e+15
3        East Asia & Pacific (excluding high income)  8.877111e+14
4                                Lower middle income  6.145184e+14
5                                              China  6.134844e+14
6  Latin America & Caribbean (excluding high income)  5.762093e+14
7                                          IDA total  2.976229e+14
8      Europe & Central Asia (excluding high income)  2.620929e+14
9                                         South Asia  2.352148e+14

In [109]:
q26 = pd.read_sql("""
    WITH country_debt AS
    (
        SELECT
            country_name,
            SUM(debt_value) AS total_debt
        FROM allcountries_debt_data
        WHERE country_name IS NOT NULL
          AND debt_value IS NOT NULL
        GROUP BY country_name
    ),
    debt_stats AS
    (
        SELECT
            AVG(total_debt) AS avg_debt,
            STDDEV(total_debt) AS std_debt
        FROM country_debt
    )
    SELECT
        c.country_name,
        c.total_debt,
        CASE
            WHEN c.total_debt > s.avg_debt + s.std_debt
                THEN 'High Debt'
            WHEN c.total_debt >= s.avg_debt
                THEN 'Medium Debt'
            ELSE 'Low Debt'
        END AS debt_category
    FROM country_debt c
    CROSS JOIN debt_stats s
    ORDER BY c.total_debt DESC;
""", engine)

display(q26)

                                    country_name    total_debt debt_category
0                            Low & middle income  2.382800e+15     High Debt
1                                  Middle income  2.314371e+15     High Debt
2                            Upper middle income  1.699829e+15     High Debt
3    East Asia & Pacific (excluding high income)  8.877111e+14     High Debt
4                            Lower middle income  6.145184e+14     High Debt
..                                           ...           ...           ...
129                              Solomon Islands  1.583295e+11      Low Debt
130                                     Dominica  1.580565e+11      Low Debt
131                                      Vanuatu  1.427487e+11      Low Debt
132                        Sao Tome and Principe  1.221988e+11      Low Debt
133                                        Tonga  8.499311e+10      Low Debt

[134 rows x 3 columns]

In [110]:
q27 = pd.read_sql("""
    WITH yearly_debt AS
    (
        SELECT
            country_name,
            year,
            SUM(debt_value) AS yearly_debt
        FROM allcountries_debt_data
        WHERE country_name IS NOT NULL
          AND debt_value IS NOT NULL
        GROUP BY country_name, year
    )
    SELECT
        country_name,
        year,
        yearly_debt,
        SUM(yearly_debt) OVER (
            PARTITION BY country_name
            ORDER BY year
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS cumulative_debt
    FROM yearly_debt
    ORDER BY country_name, year;
""", engine)

display(q27)

     country_name  year   yearly_debt  cumulative_debt
0     Afghanistan  2006  3.456692e+10     3.456692e+10
1     Afghanistan  2007  5.740144e+10     9.196836e+10
2     Afghanistan  2008  5.797651e+10     1.499449e+11
3     Afghanistan  2009  6.674058e+10     2.166854e+11
4     Afghanistan  2010  6.983335e+10     2.865188e+11
...           ...   ...           ...              ...
3552     Zimbabwe  2022  1.799662e+11     2.692749e+12
3553     Zimbabwe  2023  2.084031e+11     2.901152e+12
3554     Zimbabwe  2024  1.867728e+11     3.087925e+12
3555     Zimbabwe  2025  1.541918e+10     3.103344e+12
3556     Zimbabwe  2026  1.292328e+10     3.116267e+12

[3557 rows x 4 columns]

In [111]:
q28 = pd.read_sql("""
    SELECT
        series_name AS indicator,
        AVG(debt_value) AS average_debt
    FROM allcountries_debt_data
    WHERE series_name IS NOT NULL
      AND debt_value IS NOT NULL
    GROUP BY series_name
    HAVING AVG(debt_value) >
    (
        SELECT AVG(debt_value)
        FROM allcountries_debt_data
        WHERE debt_value IS NOT NULL
    )
    ORDER BY average_debt DESC;
""", engine)

display(q28)

                                            indicator  average_debt
0                                   GNI (current US$)  8.115100e+11
1   Imports of goods, services and primary income ...  2.335118e+11
2   Exports of goods, services and primary income ...  2.204112e+11
3      External debt stocks, total (DOD, current US$)  2.009746e+11
4         Total reserves (includes gold, current US$)  1.781573e+11
..                                                ...           ...
58  Disbursements on external debt, public and pub...  1.091438e+10
59           OPS, commercial banks (DOD, current US$)  1.041628e+10
60  Debt service on external debt, public and publ...  1.007444e+10
61  Debt service on external debt, public sector (...  1.001802e+10
62                Primary income on FDI (current US$)  9.947853e+09

[63 rows x 2 columns]

In [112]:
q29 = pd.read_sql("""
    SELECT
        country_name,
        SUM(debt_value) AS total_debt,
        ROUND(
            SUM(debt_value) * 100.0 /
            (
                SELECT SUM(debt_value)
                FROM allcountries_debt_data
                WHERE debt_value IS NOT NULL
            ),
            2
        ) AS contribution_percentage
    FROM allcountries_debt_data
    WHERE country_name IS NOT NULL
      AND debt_value IS NOT NULL
    GROUP BY country_name
    HAVING contribution_percentage > 5
    ORDER BY contribution_percentage DESC;
""", engine)

display(q29)

,country_name,total_debt,contribution_percentage
0,Low & middle income,2.382800e+15,19.12
1,Middle income,2.314371e+15,18.57
2,Upper middle income,1.699829e+15,13.64
3,East Asia & Pacific (excluding high income),8.877111e+14,7.12

In [113]:
q30 = pd.read_sql("""
    SELECT
        country_name,
        indicator,
        total_debt
    FROM
    (
        SELECT
            country_name,
            series_name AS indicator,
            SUM(debt_value) AS total_debt,
            RANK() OVER (
                PARTITION BY country_name
                ORDER BY SUM(debt_value) DESC
            ) AS indicator_rank
        FROM allcountries_debt_data
        WHERE country_name IS NOT NULL
          AND series_name IS NOT NULL
          AND debt_value IS NOT NULL
        GROUP BY country_name, series_name
    ) AS ranked_indicators
    WHERE indicator_rank = 1
    ORDER BY country_name;
""", engine)

display(q30)

    country_name          indicator    total_debt
0    Afghanistan  GNI (current US$)  2.940243e+11
1        Albania  GNI (current US$)  3.137755e+11
2        Algeria  GNI (current US$)  4.098648e+12
3         Angola  GNI (current US$)  1.582527e+12
4      Argentina  GNI (current US$)  1.018776e+13
..           ...                ...           ...
129      Vanuatu  GNI (current US$)  1.791572e+10
130     Viet Nam  GNI (current US$)  4.797914e+12
131  Yemen, Rep.  GNI (current US$)  4.455844e+11
132       Zambia  GNI (current US$)  4.357735e+11
133     Zimbabwe  GNI (current US$)  4.301723e+11

[134 rows x 3 columns]

In [115]:
import os

queries_path = "/Users/swathisri.ks/Documents/International_Debt_Analytics_DA2/app/queries.py"

print(os.path.exists(queries_path))

True

In [120]:
import sys

print(sys.executable)

/usr/local/bin/python3